project_id = "pbrhkwzdjvoflieoimlo"

[functions.get-credits]
verify_jwt = false

[functions.deduct-credits]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false
